sudo: required
services:
    - docker
    
    
before_install:
    - docker build -t backupshaik/docker-reactnew -f Dockerfile.dev .
    
    
script:
  - docker run -e CI=true backupshaik/docker-reactnew npm run test